//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int Id_gr { get; set; }
        public string Direction { get; set; }
    
        public virtual Tutor Tutor { get; set; }
        public virtual Speaker Speaker { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
