//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR_SERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LRContainer2 : DbContext
    {
        public LRContainer2()
            : base("name=LRContainer2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Speaker> SpeakerSet { get; set; }
        public DbSet<Participant> ParticipantSet { get; set; }
        public DbSet<Staff> StaffSet { get; set; }
        public DbSet<Schedule> ScheduleSet { get; set; }
        public DbSet<Tutor> TutorSet { get; set; }
        public DbSet<Groups> GroupsSet { get; set; }
    }
}
