//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR_5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LRContainer : DbContext
    {
        public LRContainer()
            : base("name=LRContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Participant> ParticipantSet { get; set; }
        public virtual DbSet<Speaker> SpeakerSet { get; set; }
        public virtual DbSet<Staff> StaffSet { get; set; }
        public virtual DbSet<Tutor> TutorSet { get; set; }
        public virtual DbSet<Schedule> ScheduleSet { get; set; }
        public virtual DbSet<Groups> GroupsSet { get; set; }
    }
}
