//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Documents { get; set; }
        public string City { get; set; }
        public string Direction { get; set; }
        public int Childrens { get; set; }
    
        public virtual User User { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
